v4l2_gpu_camera_node:
  ros__parameters:
    device: "/dev/video0"
    width: 1920
    height: 1536
    framerate: 30
    pixel_format: "YUYV"
    output_encoding: "nv12"
    buffer_count: 4
    image_topic: "image_raw"
    camera_info_topic: "camera_info"
    camera_link_frame_name: "camera0"
    optical_frame_name: "camera0_optical"
    camera_info_url: ""